apiVersion: skaffold/v2beta10
kind: Config
metadata:
  name: flask-orderlist-restapi
build:
  artifacts:
    - image: 566034038752.dkr.ecr.us-west-2.amazonaws.com/sykang/flask-orderlist-restapi
      docker:
        dockerfile: Dockerfile
  tagPolicy:
    sha256: {}
deploy:
  kubectl:
    manifests:
      - kubernetes-manifests/deployment.yaml