apiVersion: v1
kind: Namespace
metadata:
  name: flask-orderlist-restapi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-orderlist-restapi
  namespace: flask-orderlist-restapi
  labels:
    app: flask-orderlist-restapi
spec:
  selector:
    matchLabels:
      app: flask-orderlist-restapi
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: flask-orderlist-restapi
    spec:
      containers:
      - image: 566034038752.dkr.ecr.us-west-2.amazonaws.com/sykang/flask-orderlist-restapi:latest
        imagePullPolicy: Always
        name: flask-orderlist-restapi
        ports:
        - containerPort: 80
          protocol: TCP
---          
apiVersion: autoscaling/v2beta2
kind: HorizontalPodAutoscaler
metadata:
  name: flask-orderlist-restapi
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: flask-orderlist-restapi
  minReplicas: 2
  maxReplicas: 4
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          # scale up if usage is above
          # 99% of the requested CPU (100m)
          averageUtilization: 99
