apiVersion: v1
kind: Service
metadata:
  name: flask-orderlist-restapi
spec:
  selector:
    app: flask-orderlist-restapi
  type: LoadBalancer  
  ports:
   -  protocol: TCP
      port: 5050
      targetPort: 5050

