apiVersion: v1
kind: Service
metadata:
  name: flask-restapi
  namespace: orderlist
spec:
  selector:
    app: flask-restapi
  type: LoadBalancer  
  ports:
   -  protocol: TCP
      port: 80
      targetPort: 80

